# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
        - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['zip']

# GitHub release customization
release:
  prerelease: auto
